name: Buddy CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  alexa-skill:
    name: Alexa Skill CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: src/alexa-skill/package-lock.json
      - name: Install dependencies
        run: |
          cd src/alexa-skill
          npm ci
      - name: Run Build
        run: |
          cd src/alexa-skill
          npm run build

  caregiver-dashboard:
    name: Caregiver Dashboard CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: src/caregiver-dashboard/package-lock.json
      - name: Install dependencies
        run: |
          cd src/caregiver-dashboard
          npm ci
      - name: Lint
        run: |
          cd src/caregiver-dashboard
          npm run lint
      - name: Build
        run: |
          cd src/caregiver-dashboard
          npm run build
